name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run Pylint
      run: pylint calculator.py

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate coverage report
      run: |
        pytest --cov=calculator --cov-report=html test_calculator.py
        mv htmlcov coverage_report

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage_report

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag omaaartamer/python-calculator:latest

    - name: Push Docker image to Docker Hub
      run: docker push omaaartamer/python-calculator:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Deploy to Linux VM
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Pull the latest Docker image from Docker Hub
          docker pull omaaartamer/python-calculator:latest

          # Stop the existing container, if running
          docker stop calculator || true
          docker rm calculator || true

          # Run the new Docker container
          docker run -d --name calculator -p 80:80 omaaartamer/python-calculator:latest
