name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run Pylint
      run: pylint calculator.py

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}  # Use the token instead of a password
    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag your-dockerhub-omaaartamer/my-image-name:latest
    - name: Push Docker image to Docker Hub
      run: docker push your-dockerhub-omaaartamer/my-image-name:latest
