name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run Pylint
      run: pylint calculator.py  # Ensure this points to your Python script

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate coverage report
      run: |
        pytest --cov=calculator test_calculator.py 

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}  # Ensure this secret is set

    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag omaaartamer/python-calculator:latest  # Use your Docker Hub repo

    - name: Push Docker image to Docker Hub
      run: docker push omaaartamer/python-calculator:latest  # Use your Docker Hub repo
